MandarinAuction.Web/Controllers/AuctionsController.cs
#region usings

using System.Security.Claims;
using MandarinAuction.App.DTOs.Auctions;
using MandarinAuction.App.Services.Auctions;
using MandarinAuction.App.Services.Auctions.Bids;
using MandarinAuction.UIModels.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

#endregion

namespace MandarinAuction.Web.Controllers;

public class AuctionsController : Controller
{
    private const int AuctionPageIndexDefault = 1;
    private const int AuctionPageSizeDefault = 9;

    private readonly IAuctionService _auctionService;
    private readonly IAuctionBidService _auctionBidService;

    public AuctionsController(IAuctionService auctionService, IAuctionBidService auctionBidService)
    {
        _auctionService = auctionService;
        _auctionBidService = auctionBidService;
    }

    public async Task<IActionResult> Index(
        int pageIndex = AuctionPageIndexDefault,
        int pageSize = AuctionPageSizeDefault,
        bool sortAsc = true)
    {
        return View(new AuctionsViewModel
        {
            Auctions = await _auctionService.GetAll(pageIndex, pageSize, sortAsc),
            CurrentPage = pageIndex,
            TotalPages = (int)Math.Ceiling(await _auctionService.Count() / (double)pageSize)
        });
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> RaiseBid([FromBody] RaiseBidDto raiseBidDto)
    {
        await _auctionBidService.RaiseBid(
            Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!),
            raiseBidDto);

        return RedirectToAction("Index");
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> Buy([FromBody] BuyDto buyDto)
    {
        await _auctionBidService.CloseBids(buyDto.AuctionId, true);

        return RedirectToAction("Index");
    }
}

MandarinAuction.Web/Controllers/UsersController.cs
#region usings

using AutoMapper;
using MandarinAuction.App.DTOs.Users;
using MandarinAuction.App.Services.Users.Creator;
using MandarinAuction.App.Services.Users.JwtToken;
using MandarinAuction.App.Services.Users.SignIn;
using MandarinAuction.App.Validators;
using MandarinAuction.UIModels.ViewModels;
using Microsoft.AspNetCore.Mvc;

#endregion

namespace MandarinAuction.Web.Controllers;

public class UsersController : Controller
{
    private readonly SignInService _signInService;
    private readonly IUserCreatorService<UserIdentityDto> _userCreator;
    private readonly JwtTokenService _tokenService;
    private readonly IValidator<UserIdentityDto> _userIdentityValidator;
    private readonly IMapper _mapper;

    public UsersController(
        SignInService signInService,
        IUserCreatorService<UserIdentityDto> userCreator,
        JwtTokenService tokenService,
        IValidator<UserIdentityDto> userIdentityValidator,
        IMapper mapper
    )
    {
        _signInService = signInService;
        _userCreator = userCreator;
        _tokenService = tokenService;
        _userIdentityValidator = userIdentityValidator;
        _mapper = mapper;
    }

    [HttpPost]
    public async Task<IActionResult> SignIn([FromBody]AuthViewModel authViewModel, [FromQuery] string? returnUrl)
    {
        var userIdentity = _mapper.Map<UserIdentityDto>(authViewModel);

        _userIdentityValidator.Validate(userIdentity);

        return
            AuthorizeAndRedirect(
                userIdentity,
                await _signInService.Verify(userIdentity),
                returnUrl);
    }

    [HttpPost]
    public async Task<IActionResult> Registration([FromBody]AuthViewModel authViewModel, [FromQuery] string? returnUrl)
    {
        var userIdentity = _mapper.Map<UserIdentityDto>(authViewModel);

        _userIdentityValidator.Validate(userIdentity);

        return
            AuthorizeAndRedirect(
                userIdentity,
                await _userCreator.Create(userIdentity),
                returnUrl);
    }

    private IActionResult AuthorizeAndRedirect(UserIdentityDto userDto, Guid userId, string? returnUrl)
    {
        _tokenService.SaveCookie(
            HttpContext,
            _tokenService.GenerateToken(userDto, userId)
        );

        return RedirectToLocalUrl(returnUrl);
    }

    private IActionResult RedirectToLocalUrl(string? returnUrl)
    {
        if (!string.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
        {
            return Redirect(returnUrl);
        }

        return Redirect("/");
    }
}

MandarinAuction.Web/Views/Auctions/Index.cshtml
@model MandarinAuction.UIModels.ViewModels.AuctionsViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="main-content">
    <div>
        <div class="modal fade" id="bidMandarinModal" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="w-100 text-center">
                            <h5>Покупка мандарина</h5>
                        </div>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div>
                            <form method="post" class="row" id="RaiseBidForm" action="@Url.Action("RaiseBid")">
                                <div class="mb-3">
                                    <input type="hidden" id="auctionId" name="auctionId" value="" />
                                    <label for="mandarinBidSum" class="form-label">Сумма ставки:</label>
                                    <div class="d-flex col-8">
                                        <input type="number" class="form-control me-2" id="mandarinBidSum" name="bidSum" required />
                                        <span class="form input-suffix">р.</span>
                                    </div>
                                </div>
                                <span id="raiseBidErrors"></span>
                                <div class="d-flex mt-2">
                                    <button type="submit" class="btn btn-dark" id="RaiseBidBtn">
                                        Сделать ставку
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="main-content-body">
        <div class="main-body-lots row justify-content-center">
            @if (Model.Auctions != null)
            {
                @foreach (var auction in Model.Auctions)
                {
                    <div class="lots-item col p-2">
                        <div class="card text-white bg-dark lots-item-card">
                            <img class="card-img-top" src="@auction!.Mandarin.ImageUrl" alt="orange mandarin">
                            <div class="card-body">
                                <span>Статус аукциона: @(auction.IsClosed ? "Закрыт" : "Открыт") </span>
                                <h5 class="card-title">@auction.Mandarin.Name</h5>
                                <p class="card-text card-text-limited">
                                    @auction.Mandarin.Description
                                </p>
                                <div class="row">
                                    <div class="d-flex justify-content-between lots-item__price">
                                        <span>Последняя ставка: </span>
                                        <div>
                                            <span class="lots-item__price">@auction.BidSum</span>
                                            <span class="lots-item__price">Р.</span>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-between lots-item__price">
                                        <span>Сумма выкупа:</span>
                                        <div>
                                            <span class="lots-item__price">@auction.BuySum</span>
                                            <span class="lots-item__price">Р.</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-between mt-3">
                                    <button type="button"
                                            class="btn btn-primary btn-light"
                                            data-bs-toggle="modal"
                                            data-bs-target="#bidMandarinModal"
                                            data-bid-sum="@auction.BidSum"
                                            data-auction-id="@auction.Id">
                                        Поднять ставку
                                    </button>
                                    <button type="button"
                                            class="btn btn-primary btn-light"
                                            data-buy-sum="@auction.BuySum"
                                            data-auction-id="@auction.Id">
                                        Выкупить
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                @if (Model.HasPreviousPage)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index",new {pageIndex = Model.CurrentPage - 1})">Предыдущая</a>
                    </li>
                }

                @for (var i = 1; i <= Model.TotalPages; i++)
                {
                    <li class="page-item @(Model.CurrentPage == i ? "active" : "")">
                        <a class="page-link" href="@Url.Action("Index", new {pageIndex = i})">@i</a>
                    </li>
                }

                @if (Model.HasNextPage)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", new { pageIndex = Model.CurrentPage + 1 })">Следующая</a>
                    </li>
                }
            </ul>
        </nav>
    </div>
</div>

MandarinAuction.Web/Views/Shared/_Layout.cshtml
@model MandarinAuction.UIModels.ViewModels.AuthViewModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MandarinAuction.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auctions" asp-action="Index">Home</a>
                    </ul>
                    @if (!User.Identity!.IsAuthenticated)
                    {
                        <div class="profile-item d-flex mt-3 mt-sm-0 d-sm-block justify-content-between">
                            <button class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#authModal" type="button">Войти</button>
                        </div>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @{await Html.RenderPartialAsync("../Users/Auth", Model);}
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MandarinAuction.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script asp-append-version="true" src="~/js/auth.js"></script>
    <script asp-append-version="true" src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MandarinAuction.Web/Views/Users/Auth.cshtml
@model MandarinAuction.UIModels.ViewModels.AuthViewModel

<div class="modal fade" id="authModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <div class="w-100 text-center">
                    <h5>Вход в систему</h5>
                </div>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div>
                    <div>
                        <form method="post" class="row" id="authForm" action="#">
                            <div class="mb-3">
                                <label for="Email" class="form-label">Email</label>
                                <input type="email" class="form-control" id="Email" name="Email" required />
                                <span class="text-danger" asp-validation-for="Email"></span>
                            </div>
                            <div class="mb-3">
                                <label for="Password" class="form-label">Password</label>
                                <input type="password" class="form-control" id="Password" name="Password" required />
                                <span class="text-danger" asp-validation-for="Password"></span>
                            </div>
                            <span id="authErrors"></span>
                            <div class="d-flex justify-content-between">
                                <button type="submit" class="btn btn-dark" id="signInBtn"
                                        data-action="@Url.Action("SignIn", "Users")">
                                    Войти
                                </button>
                                <button type="submit" class="btn btn-dark" id="registrationBtn"
                                        data-action="@Url.Action("Registration", "Users")">
                                    Зарегистрироваться
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>